### ISSUE TITLE
GitHub Terms of Service violation

### ISSUE THREAD

**Issue by appgurueu** [Tim79000/BloodTest#2]
Your ["license"](https://github.com/Tim79000/Bloodathon/blob/main/License.txt) clearly violates the [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users):

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. **By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).**

(emphasis mine)

Please fix your license; otherwise you may be reported for the ToS violation.

**Comment by Tim79000** [comment]
It is now currently unlicensed, will relicense under MIT soon.
